%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'EBASELINE';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EBASELINE.log');
M_.exo_names = 'ex_lab_fall';
M_.exo_names_tex = 'ex\_lab\_fall';
M_.exo_names_long = 'ex_lab_fall';
M_.exo_names = char(M_.exo_names, 'ex_xx');
M_.exo_names_tex = char(M_.exo_names_tex, 'ex\_xx');
M_.exo_names_long = char(M_.exo_names_long, 'ex_xx');
M_.exo_names = char(M_.exo_names, 'ex_gdp');
M_.exo_names_tex = char(M_.exo_names_tex, 'ex\_gdp');
M_.exo_names_long = char(M_.exo_names_long, 'ex_gdp');
M_.exo_names = char(M_.exo_names, 'eps_inv');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_inv');
M_.exo_names_long = char(M_.exo_names_long, 'eps_inv');
M_.exo_names = char(M_.exo_names, 'eps_yo');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_yo');
M_.exo_names_long = char(M_.exo_names_long, 'eps_yo');
M_.endo_names = 'LAMBDA';
M_.endo_names_tex = 'LAMBDA';
M_.endo_names_long = 'LAMBDA';
M_.endo_names = char(M_.endo_names, 'LAMBDAROT');
M_.endo_names_tex = char(M_.endo_names_tex, 'LAMBDAROT');
M_.endo_names_long = char(M_.endo_names_long, 'LAMBDAROT');
M_.endo_names = char(M_.endo_names, 'LOPT');
M_.endo_names_tex = char(M_.endo_names_tex, 'LOPT');
M_.endo_names_long = char(M_.endo_names_long, 'LOPT');
M_.endo_names = char(M_.endo_names, 'LROT');
M_.endo_names_tex = char(M_.endo_names_tex, 'LROT');
M_.endo_names_long = char(M_.endo_names_long, 'LROT');
M_.endo_names = char(M_.endo_names, 'COPT');
M_.endo_names_tex = char(M_.endo_names_tex, 'COPT');
M_.endo_names_long = char(M_.endo_names_long, 'COPT');
M_.endo_names = char(M_.endo_names, 'CROT');
M_.endo_names_tex = char(M_.endo_names_tex, 'CROT');
M_.endo_names_long = char(M_.endo_names_long, 'CROT');
M_.endo_names = char(M_.endo_names, 'PN');
M_.endo_names_tex = char(M_.endo_names_tex, 'PN');
M_.endo_names_long = char(M_.endo_names_long, 'PN');
M_.endo_names = char(M_.endo_names, 'S');
M_.endo_names_tex = char(M_.endo_names_tex, 'S');
M_.endo_names_long = char(M_.endo_names_long, 'S');
M_.endo_names = char(M_.endo_names, 'PG');
M_.endo_names_tex = char(M_.endo_names_tex, 'PG');
M_.endo_names_long = char(M_.endo_names_long, 'PG');
M_.endo_names = char(M_.endo_names, 'W');
M_.endo_names_tex = char(M_.endo_names_tex, 'W');
M_.endo_names_long = char(M_.endo_names_long, 'W');
M_.endo_names = char(M_.endo_names, 'WN');
M_.endo_names_tex = char(M_.endo_names_tex, 'WN');
M_.endo_names_long = char(M_.endo_names_long, 'WN');
M_.endo_names = char(M_.endo_names, 'WT');
M_.endo_names_tex = char(M_.endo_names_tex, 'WT');
M_.endo_names_long = char(M_.endo_names_long, 'WT');
M_.endo_names = char(M_.endo_names, 'YN');
M_.endo_names_tex = char(M_.endo_names_tex, 'YN');
M_.endo_names_long = char(M_.endo_names_long, 'YN');
M_.endo_names = char(M_.endo_names, 'KN');
M_.endo_names_tex = char(M_.endo_names_tex, 'KN');
M_.endo_names_long = char(M_.endo_names_long, 'KN');
M_.endo_names = char(M_.endo_names, 'IN');
M_.endo_names_tex = char(M_.endo_names_tex, 'IN');
M_.endo_names_long = char(M_.endo_names_long, 'IN');
M_.endo_names = char(M_.endo_names, 'QN');
M_.endo_names_tex = char(M_.endo_names_tex, 'QN');
M_.endo_names_long = char(M_.endo_names_long, 'QN');
M_.endo_names = char(M_.endo_names, 'LNN');
M_.endo_names_tex = char(M_.endo_names_tex, 'LNN');
M_.endo_names_long = char(M_.endo_names_long, 'LNN');
M_.endo_names = char(M_.endo_names, 'OMEGAN');
M_.endo_names_tex = char(M_.endo_names_tex, 'OMEGAN');
M_.endo_names_long = char(M_.endo_names_long, 'OMEGAN');
M_.endo_names = char(M_.endo_names, 'YT');
M_.endo_names_tex = char(M_.endo_names_tex, 'YT');
M_.endo_names_long = char(M_.endo_names_long, 'YT');
M_.endo_names = char(M_.endo_names, 'ZT');
M_.endo_names_tex = char(M_.endo_names_tex, 'ZT');
M_.endo_names_long = char(M_.endo_names_long, 'ZT');
M_.endo_names = char(M_.endo_names, 'KT');
M_.endo_names_tex = char(M_.endo_names_tex, 'KT');
M_.endo_names_long = char(M_.endo_names_long, 'KT');
M_.endo_names = char(M_.endo_names, 'IT');
M_.endo_names_tex = char(M_.endo_names_tex, 'IT');
M_.endo_names_long = char(M_.endo_names_long, 'IT');
M_.endo_names = char(M_.endo_names, 'QT');
M_.endo_names_tex = char(M_.endo_names_tex, 'QT');
M_.endo_names_long = char(M_.endo_names_long, 'QT');
M_.endo_names = char(M_.endo_names, 'LT');
M_.endo_names_tex = char(M_.endo_names_tex, 'LT');
M_.endo_names_long = char(M_.endo_names_long, 'LT');
M_.endo_names = char(M_.endo_names, 'OMEGAT');
M_.endo_names_tex = char(M_.endo_names_tex, 'OMEGAT');
M_.endo_names_long = char(M_.endo_names_long, 'OMEGAT');
M_.endo_names = char(M_.endo_names, 'GI');
M_.endo_names_tex = char(M_.endo_names_tex, 'GI');
M_.endo_names_long = char(M_.endo_names_long, 'GI');
M_.endo_names = char(M_.endo_names, 'KG');
M_.endo_names_tex = char(M_.endo_names_tex, 'KG');
M_.endo_names_long = char(M_.endo_names_long, 'KG');
M_.endo_names = char(M_.endo_names, 'GC');
M_.endo_names_tex = char(M_.endo_names_tex, 'GC');
M_.endo_names_long = char(M_.endo_names_long, 'GC');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'TAUL');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAUL');
M_.endo_names_long = char(M_.endo_names_long, 'TAUL');
M_.endo_names = char(M_.endo_names, 'TAUC');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAUC');
M_.endo_names_long = char(M_.endo_names_long, 'TAUC');
M_.endo_names = char(M_.endo_names, 'TAX');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAX');
M_.endo_names_long = char(M_.endo_names_long, 'TAX');
M_.endo_names = char(M_.endo_names, 'B');
M_.endo_names_tex = char(M_.endo_names_tex, 'B');
M_.endo_names_long = char(M_.endo_names_long, 'B');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'INV');
M_.endo_names_tex = char(M_.endo_names_tex, 'INV');
M_.endo_names_long = char(M_.endo_names_long, 'INV');
M_.endo_names = char(M_.endo_names, 'DN');
M_.endo_names_tex = char(M_.endo_names_tex, 'DN');
M_.endo_names_long = char(M_.endo_names_long, 'DN');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'YNON');
M_.endo_names_tex = char(M_.endo_names_tex, 'YNON');
M_.endo_names_long = char(M_.endo_names_long, 'YNON');
M_.endo_names = char(M_.endo_names, 'TSUR');
M_.endo_names_tex = char(M_.endo_names_tex, 'TSUR');
M_.endo_names_long = char(M_.endo_names_long, 'TSUR');
M_.endo_names = char(M_.endo_names, 'CAD');
M_.endo_names_tex = char(M_.endo_names_tex, 'CAD');
M_.endo_names_long = char(M_.endo_names_long, 'CAD');
M_.endo_names = char(M_.endo_names, 'FSTAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'FSTAR');
M_.endo_names_long = char(M_.endo_names_long, 'FSTAR');
M_.endo_names = char(M_.endo_names, 'GSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'GSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'GSHARE');
M_.endo_names = char(M_.endo_names, 'GCSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'GCSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'GCSHARE');
M_.endo_names = char(M_.endo_names, 'GISHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'GISHARE');
M_.endo_names_long = char(M_.endo_names_long, 'GISHARE');
M_.endo_names = char(M_.endo_names, 'ZSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'ZSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'ZSHARE');
M_.endo_names = char(M_.endo_names, 'BSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'BSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'BSHARE');
M_.endo_names = char(M_.endo_names, 'TSURSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'TSURSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'TSURSHARE');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'GITILDE');
M_.endo_names_tex = char(M_.endo_names_tex, 'GITILDE');
M_.endo_names_long = char(M_.endo_names_long, 'GITILDE');
M_.endo_names = char(M_.endo_names, 'YNONSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'YNONSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'YNONSHARE');
M_.endo_names = char(M_.endo_names, 'TAXSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAXSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'TAXSHARE');
M_.endo_names = char(M_.endo_names, 'NUT');
M_.endo_names_tex = char(M_.endo_names_tex, 'NUT');
M_.endo_names_long = char(M_.endo_names_long, 'NUT');
M_.endo_names = char(M_.endo_names, 'TAXNON');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAXNON');
M_.endo_names_long = char(M_.endo_names_long, 'TAXNON');
M_.endo_names = char(M_.endo_names, 'CADSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'CADSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'CADSHARE');
M_.endo_names = char(M_.endo_names, 'FSTARSHARE');
M_.endo_names_tex = char(M_.endo_names_tex, 'FSTARSHARE');
M_.endo_names_long = char(M_.endo_names_long, 'FSTARSHARE');
M_.endo_names = char(M_.endo_names, 'RKG');
M_.endo_names_tex = char(M_.endo_names_tex, 'RKG');
M_.endo_names_long = char(M_.endo_names_long, 'RKG');
M_.endo_names = char(M_.endo_names, 'EPSILON');
M_.endo_names_tex = char(M_.endo_names_tex, 'EPSILON');
M_.endo_names_long = char(M_.endo_names_long, 'EPSILON');
M_.endo_names = char(M_.endo_names, 'DELTAGT');
M_.endo_names_tex = char(M_.endo_names_tex, 'DELTAGT');
M_.endo_names_long = char(M_.endo_names_long, 'DELTAGT');
M_.endo_names = char(M_.endo_names, 'ASTAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'ASTAR');
M_.endo_names_long = char(M_.endo_names_long, 'ASTAR');
M_.endo_names = char(M_.endo_names, 'RSTAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'RSTAR');
M_.endo_names_long = char(M_.endo_names_long, 'RSTAR');
M_.endo_names = char(M_.endo_names, 'BOPT');
M_.endo_names_tex = char(M_.endo_names_tex, 'BOPT');
M_.endo_names_long = char(M_.endo_names_long, 'BOPT');
M_.endo_names = char(M_.endo_names, 'RDC');
M_.endo_names_tex = char(M_.endo_names_tex, 'RDC');
M_.endo_names_long = char(M_.endo_names_long, 'RDC');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'DC');
M_.endo_names_tex = char(M_.endo_names_tex, 'DC');
M_.endo_names_long = char(M_.endo_names_long, 'DC');
M_.endo_names = char(M_.endo_names, 'BSTAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'BSTAR');
M_.endo_names_long = char(M_.endo_names_long, 'BSTAR');
M_.endo_names = char(M_.endo_names, 'GR');
M_.endo_names_tex = char(M_.endo_names_tex, 'GR');
M_.endo_names_long = char(M_.endo_names_long, 'GR');
M_.endo_names = char(M_.endo_names, 'GAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'GAP');
M_.endo_names_long = char(M_.endo_names_long, 'GAP');
M_.endo_names = char(M_.endo_names, 'TAUCTAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAUCTAR');
M_.endo_names_long = char(M_.endo_names_long, 'TAUCTAR');
M_.endo_names = char(M_.endo_names, 'TAULTAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAULTAR');
M_.endo_names_long = char(M_.endo_names_long, 'TAULTAR');
M_.endo_names = char(M_.endo_names, 'GCTAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'GCTAR');
M_.endo_names_long = char(M_.endo_names_long, 'GCTAR');
M_.endo_names = char(M_.endo_names, 'ZTAR');
M_.endo_names_tex = char(M_.endo_names_tex, 'ZTAR');
M_.endo_names_long = char(M_.endo_names_long, 'ZTAR');
M_.endo_names = char(M_.endo_names, 'TAUCRULE');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAUCRULE');
M_.endo_names_long = char(M_.endo_names_long, 'TAUCRULE');
M_.endo_names = char(M_.endo_names, 'TAULRULE');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAULRULE');
M_.endo_names_long = char(M_.endo_names_long, 'TAULRULE');
M_.endo_names = char(M_.endo_names, 'GCRULE');
M_.endo_names_tex = char(M_.endo_names_tex, 'GCRULE');
M_.endo_names_long = char(M_.endo_names_long, 'GCRULE');
M_.endo_names = char(M_.endo_names, 'ZRULE');
M_.endo_names_tex = char(M_.endo_names_tex, 'ZRULE');
M_.endo_names_long = char(M_.endo_names_long, 'ZRULE');
M_.endo_names = char(M_.endo_names, 'RKN');
M_.endo_names_tex = char(M_.endo_names_tex, 'RKN');
M_.endo_names_long = char(M_.endo_names_long, 'RKN');
M_.endo_names = char(M_.endo_names, 'RKT');
M_.endo_names_tex = char(M_.endo_names_tex, 'RKT');
M_.endo_names_long = char(M_.endo_names_long, 'RKT');
M_.endo_names = char(M_.endo_names, 'MCN');
M_.endo_names_tex = char(M_.endo_names_tex, 'MCN');
M_.endo_names_long = char(M_.endo_names_long, 'MCN');
M_.endo_names = char(M_.endo_names, 'MCT');
M_.endo_names_tex = char(M_.endo_names_tex, 'MCT');
M_.endo_names_long = char(M_.endo_names_long, 'MCT');
M_.endo_names = char(M_.endo_names, 'PIEN');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIEN');
M_.endo_names_long = char(M_.endo_names_long, 'PIEN');
M_.endo_names = char(M_.endo_names, 'PIET');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIET');
M_.endo_names_long = char(M_.endo_names_long, 'PIET');
M_.endo_names = char(M_.endo_names, 'PIE');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIE');
M_.endo_names_long = char(M_.endo_names_long, 'PIE');
M_.endo_names = char(M_.endo_names, 'RN');
M_.endo_names_tex = char(M_.endo_names_tex, 'RN');
M_.endo_names_long = char(M_.endo_names_long, 'RN');
M_.endo_names = char(M_.endo_names, 'GISHARE_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'GISHARE\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'GISHARE_CHANGE');
M_.endo_names = char(M_.endo_names, 'ASTARSHARE_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'ASTARSHARE\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'ASTARSHARE_CHANGE');
M_.endo_names = char(M_.endo_names, 'GRSHARE_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'GRSHARE\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'GRSHARE_CHANGE');
M_.endo_names = char(M_.endo_names, 'PN_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'PN\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'PN_DEV');
M_.endo_names = char(M_.endo_names, 'TAUC_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAUC\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'TAUC_DEV');
M_.endo_names = char(M_.endo_names, 'TAUL_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAUL\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'TAUL_DEV');
M_.endo_names = char(M_.endo_names, 'ZSHARE_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'ZSHARE\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'ZSHARE_CHANGE');
M_.endo_names = char(M_.endo_names, 'GCSHARE_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'GCSHARE\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'GCSHARE_CHANGE');
M_.endo_names = char(M_.endo_names, 'R_NET');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_NET');
M_.endo_names_long = char(M_.endo_names_long, 'R_NET');
M_.endo_names = char(M_.endo_names, 'INV_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'INV\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'INV_DEV');
M_.endo_names = char(M_.endo_names, 'C_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'C_DEV');
M_.endo_names = char(M_.endo_names, 'W_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'W\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'W_DEV');
M_.endo_names = char(M_.endo_names, 'L_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'L_DEV');
M_.endo_names = char(M_.endo_names, 'KG_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'KG\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'KG_DEV');
M_.endo_names = char(M_.endo_names, 'K_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'K_DEV');
M_.endo_names = char(M_.endo_names, 'Y_GROWTH');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_GROWTH');
M_.endo_names_long = char(M_.endo_names_long, 'Y_GROWTH');
M_.endo_names = char(M_.endo_names, 'YT_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'YT\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'YT_DEV');
M_.endo_names = char(M_.endo_names, 'YN_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'YN\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'YN_DEV');
M_.endo_names = char(M_.endo_names, 'DSHARE_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'DSHARE\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'DSHARE_DEV');
M_.endo_names = char(M_.endo_names, 'DCSHARE_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'DCSHARE\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'DCSHARE_DEV');
M_.endo_names = char(M_.endo_names, 'BSHARE_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'BSHARE\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'BSHARE_DEV');
M_.endo_names = char(M_.endo_names, 'TOTPUBDEBT_PER');
M_.endo_names_tex = char(M_.endo_names_tex, 'TOTPUBDEBT\_PER');
M_.endo_names_long = char(M_.endo_names_long, 'TOTPUBDEBT_PER');
M_.endo_names = char(M_.endo_names, 'S_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'S\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'S_DEV');
M_.endo_names = char(M_.endo_names, 'FSTAR_PER');
M_.endo_names_tex = char(M_.endo_names_tex, 'FSTAR\_PER');
M_.endo_names_long = char(M_.endo_names_long, 'FSTAR_PER');
M_.endo_names = char(M_.endo_names, 'DELTAGT_PER');
M_.endo_names_tex = char(M_.endo_names_tex, 'DELTAGT\_PER');
M_.endo_names_long = char(M_.endo_names_long, 'DELTAGT_PER');
M_.endo_names = char(M_.endo_names, 'EPSILON_PER');
M_.endo_names_tex = char(M_.endo_names_tex, 'EPSILON\_PER');
M_.endo_names_long = char(M_.endo_names_long, 'EPSILON_PER');
M_.endo_names = char(M_.endo_names, 'YNON_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'YNON\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'YNON_DEV');
M_.endo_names = char(M_.endo_names, 'CADSHARE_PER');
M_.endo_names_tex = char(M_.endo_names_tex, 'CADSHARE\_PER');
M_.endo_names_long = char(M_.endo_names_long, 'CADSHARE_PER');
M_.endo_names = char(M_.endo_names, 'GI_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'GI\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'GI_DEV');
M_.endo_names = char(M_.endo_names, 'Z_SHAREY');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z\_SHAREY');
M_.endo_names_long = char(M_.endo_names_long, 'Z_SHAREY');
M_.endo_names = char(M_.endo_names, 'GC_SHAREY');
M_.endo_names_tex = char(M_.endo_names_tex, 'GC\_SHAREY');
M_.endo_names_long = char(M_.endo_names_long, 'GC_SHAREY');
M_.endo_names = char(M_.endo_names, 'Z_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'Z_DEV');
M_.endo_names = char(M_.endo_names, 'GC_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'GC\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'GC_DEV');
M_.endo_names = char(M_.endo_names, 'GI_GROWTH');
M_.endo_names_tex = char(M_.endo_names_tex, 'GI\_GROWTH');
M_.endo_names_long = char(M_.endo_names_long, 'GI_GROWTH');
M_.endo_names = char(M_.endo_names, 'YNON_GROWTH');
M_.endo_names_tex = char(M_.endo_names_tex, 'YNON\_GROWTH');
M_.endo_names_long = char(M_.endo_names_long, 'YNON_GROWTH');
M_.endo_names = char(M_.endo_names, 'PIE_RATE');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIE\_RATE');
M_.endo_names_long = char(M_.endo_names_long, 'PIE_RATE');
M_.endo_names = char(M_.endo_names, 'TOTREV');
M_.endo_names_tex = char(M_.endo_names_tex, 'TOTREV');
M_.endo_names_long = char(M_.endo_names_long, 'TOTREV');
M_.endo_names = char(M_.endo_names, 'TOTEXP');
M_.endo_names_tex = char(M_.endo_names_tex, 'TOTEXP');
M_.endo_names_long = char(M_.endo_names_long, 'TOTEXP');
M_.endo_names = char(M_.endo_names, 'PT');
M_.endo_names_tex = char(M_.endo_names_tex, 'PT');
M_.endo_names_long = char(M_.endo_names_long, 'PT');
M_.endo_names = char(M_.endo_names, 'PTH');
M_.endo_names_tex = char(M_.endo_names_tex, 'PTH');
M_.endo_names_long = char(M_.endo_names_long, 'PTH');
M_.endo_names = char(M_.endo_names, 'PTG');
M_.endo_names_tex = char(M_.endo_names_tex, 'PTG');
M_.endo_names_long = char(M_.endo_names_long, 'PTG');
M_.endo_names = char(M_.endo_names, 'PIETH');
M_.endo_names_tex = char(M_.endo_names_tex, 'PIETH');
M_.endo_names_long = char(M_.endo_names_long, 'PIETH');
M_.endo_names = char(M_.endo_names, 'XX');
M_.endo_names_tex = char(M_.endo_names_tex, 'XX');
M_.endo_names_long = char(M_.endo_names_long, 'XX');
M_.endo_names = char(M_.endo_names, 'XX_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'XX\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'XX_CHANGE');
M_.endo_names = char(M_.endo_names, 'taukoff');
M_.endo_names_tex = char(M_.endo_names_tex, 'taukoff');
M_.endo_names_long = char(M_.endo_names_long, 'taukoff');
M_.endo_names = char(M_.endo_names, 'CROT_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'CROT\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'CROT_DEV');
M_.endo_names = char(M_.endo_names, 'TAXSHARE_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAXSHARE\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'TAXSHARE_CHANGE');
M_.endo_names = char(M_.endo_names, 'D_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'D\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'D_DEV');
M_.endo_names = char(M_.endo_names, 'DC_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'DC\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'DC_DEV');
M_.endo_names = char(M_.endo_names, 'B_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'B\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'B_DEV');
M_.endo_names = char(M_.endo_names, 'TAXNON_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'TAXNON\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'TAXNON_DEV');
M_.endo_names = char(M_.endo_names, 'Y_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'Y_DEV');
M_.endo_names = char(M_.endo_names, 'Y_YOY');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_YOY');
M_.endo_names_long = char(M_.endo_names_long, 'Y_YOY');
M_.endo_names = char(M_.endo_names, 'SRP_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'SRP\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'SRP_CHANGE');
M_.endo_names = char(M_.endo_names, 'REMIT_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'REMIT\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'REMIT_CHANGE');
M_.endo_names = char(M_.endo_names, 'COPT_DEV');
M_.endo_names_tex = char(M_.endo_names_tex, 'COPT\_DEV');
M_.endo_names_long = char(M_.endo_names_long, 'COPT_DEV');
M_.endo_names = char(M_.endo_names, 'Saving');
M_.endo_names_tex = char(M_.endo_names_tex, 'Saving');
M_.endo_names_long = char(M_.endo_names_long, 'Saving');
M_.endo_names = char(M_.endo_names, 'S_CHANGE');
M_.endo_names_tex = char(M_.endo_names_tex, 'S\_CHANGE');
M_.endo_names_long = char(M_.endo_names_long, 'S_CHANGE');
M_.endo_names = char(M_.endo_names, 'GSaving');
M_.endo_names_tex = char(M_.endo_names_tex, 'GSaving');
M_.endo_names_long = char(M_.endo_names_long, 'GSaving');
M_.endo_names = char(M_.endo_names, 'NIIP');
M_.endo_names_tex = char(M_.endo_names_tex, 'NIIP');
M_.endo_names_long = char(M_.endo_names_long, 'NIIP');
M_.endo_names = char(M_.endo_names, 'T2');
M_.endo_names_tex = char(M_.endo_names_tex, 'T2');
M_.endo_names_long = char(M_.endo_names_long, 'T2');
M_.endo_names = char(M_.endo_names, 'MM_TOTAL');
M_.endo_names_tex = char(M_.endo_names_tex, 'MM\_TOTAL');
M_.endo_names_long = char(M_.endo_names_long, 'MM_TOTAL');
M_.endo_names = char(M_.endo_names, 'Gov_sub');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gov\_sub');
M_.endo_names_long = char(M_.endo_names_long, 'Gov_sub');
M_.endo_names = char(M_.endo_names, 'PTH_S');
M_.endo_names_tex = char(M_.endo_names_tex, 'PTH\_S');
M_.endo_names_long = char(M_.endo_names_long, 'PTH_S');
M_.endo_names = char(M_.endo_names, 'EPSILONM');
M_.endo_names_tex = char(M_.endo_names_tex, 'EPSILONM');
M_.endo_names_long = char(M_.endo_names_long, 'EPSILONM');
M_.endo_names = char(M_.endo_names, 'YDOM');
M_.endo_names_tex = char(M_.endo_names_tex, 'YDOM');
M_.endo_names_long = char(M_.endo_names_long, 'YDOM');
M_.endo_names = char(M_.endo_names, 'loan_sum');
M_.endo_names_tex = char(M_.endo_names_tex, 'loan\_sum');
M_.endo_names_long = char(M_.endo_names_long, 'loan_sum');
M_.endo_names = char(M_.endo_names, 'OB');
M_.endo_names_tex = char(M_.endo_names_tex, 'OB');
M_.endo_names_long = char(M_.endo_names_long, 'OB');
M_.endo_names = char(M_.endo_names, 'tauk');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauk');
M_.endo_names_long = char(M_.endo_names_long, 'tauk');
M_.endo_names = char(M_.endo_names, 'varphi');
M_.endo_names_tex = char(M_.endo_names_tex, 'varphi');
M_.endo_names_long = char(M_.endo_names_long, 'varphi');
M_.endo_names = char(M_.endo_names, 'nu');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu');
M_.endo_names_long = char(M_.endo_names_long, 'nu');
M_.endo_names = char(M_.endo_names, 'betaa');
M_.endo_names_tex = char(M_.endo_names_tex, 'betaa');
M_.endo_names_long = char(M_.endo_names_long, 'betaa');
M_.endo_names = char(M_.endo_names, 'delta');
M_.endo_names_tex = char(M_.endo_names_tex, 'delta');
M_.endo_names_long = char(M_.endo_names_long, 'delta');
M_.endo_names = char(M_.endo_names, 'rem');
M_.endo_names_tex = char(M_.endo_names_tex, 'rem');
M_.endo_names_long = char(M_.endo_names_long, 'rem');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'upsilondc');
M_.endo_names_tex = char(M_.endo_names_tex, 'upsilondc');
M_.endo_names_long = char(M_.endo_names_long, 'upsilondc');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'rd');
M_.endo_names_tex = char(M_.endo_names_tex, 'rd');
M_.endo_names_long = char(M_.endo_names_long, 'rd');
M_.endo_names = char(M_.endo_names, 'varthetakappa');
M_.endo_names_tex = char(M_.endo_names_tex, 'varthetakappa');
M_.endo_names_long = char(M_.endo_names_long, 'varthetakappa');
M_.endo_names = char(M_.endo_names, 'zn');
M_.endo_names_tex = char(M_.endo_names_tex, 'zn');
M_.endo_names_long = char(M_.endo_names_long, 'zn');
M_.endo_names = char(M_.endo_names, 'kappaopt');
M_.endo_names_tex = char(M_.endo_names_tex, 'kappaopt');
M_.endo_names_long = char(M_.endo_names_long, 'kappaopt');
M_.endo_names = char(M_.endo_names, 'kapparot');
M_.endo_names_tex = char(M_.endo_names_tex, 'kapparot');
M_.endo_names_long = char(M_.endo_names_long, 'kapparot');
M_.endo_names = char(M_.endo_names, 'MM_K');
M_.endo_names_tex = char(M_.endo_names_tex, 'MM\_K');
M_.endo_names_long = char(M_.endo_names_long, 'MM_K');
M_.endo_names = char(M_.endo_names, 'temp1');
M_.endo_names_tex = char(M_.endo_names_tex, 'temp1');
M_.endo_names_long = char(M_.endo_names_long, 'temp1');
M_.endo_names = char(M_.endo_names, 'ex_yy');
M_.endo_names_tex = char(M_.endo_names_tex, 'ex\_yy');
M_.endo_names_long = char(M_.endo_names_long, 'ex_yy');
M_.endo_names = char(M_.endo_names, 'ex_sick');
M_.endo_names_tex = char(M_.endo_names_tex, 'ex\_sick');
M_.endo_names_long = char(M_.endo_names_long, 'ex_sick');
M_.endo_partitions = struct();
M_.param_names = 'ggamma';
M_.param_names_tex = 'ggamma';
M_.param_names_long = 'ggamma';
M_.param_names = char(M_.param_names, 'share_exp');
M_.param_names_tex = char(M_.param_names_tex, 'share\_exp');
M_.param_names_long = char(M_.param_names_long, 'share_exp');
M_.param_names = char(M_.param_names, 'share_imp');
M_.param_names_tex = char(M_.param_names_tex, 'share\_imp');
M_.param_names_long = char(M_.param_names_long, 'share_imp');
M_.param_names = char(M_.param_names, 'share_gc');
M_.param_names_tex = char(M_.param_names_tex, 'share\_gc');
M_.param_names_long = char(M_.param_names_long, 'share_gc');
M_.param_names = char(M_.param_names, 'share_g');
M_.param_names_tex = char(M_.param_names_tex, 'share\_g');
M_.param_names_long = char(M_.param_names_long, 'share_g');
M_.param_names = char(M_.param_names, 'share_i');
M_.param_names_tex = char(M_.param_names_tex, 'share\_i');
M_.param_names_long = char(M_.param_names_long, 'share_i');
M_.param_names = char(M_.param_names, 'share_gdpo');
M_.param_names_tex = char(M_.param_names_tex, 'share\_gdpo');
M_.param_names_long = char(M_.param_names_long, 'share_gdpo');
M_.param_names = char(M_.param_names, 'share_fstar');
M_.param_names_tex = char(M_.param_names_tex, 'share\_fstar');
M_.param_names_long = char(M_.param_names_long, 'share_fstar');
M_.param_names = char(M_.param_names, 'share_b');
M_.param_names_tex = char(M_.param_names_tex, 'share\_b');
M_.param_names_long = char(M_.param_names_long, 'share_b');
M_.param_names = char(M_.param_names, 'trad_g');
M_.param_names_tex = char(M_.param_names_tex, 'trad\_g');
M_.param_names_long = char(M_.param_names_long, 'trad_g');
M_.param_names = char(M_.param_names, 'trad_c');
M_.param_names_tex = char(M_.param_names_tex, 'trad\_c');
M_.param_names_long = char(M_.param_names_long, 'trad_c');
M_.param_names = char(M_.param_names, 'r_net');
M_.param_names_tex = char(M_.param_names_tex, 'r\_net');
M_.param_names_long = char(M_.param_names_long, 'r_net');
M_.param_names = char(M_.param_names, 'rstar_net');
M_.param_names_tex = char(M_.param_names_tex, 'rstar\_net');
M_.param_names_long = char(M_.param_names_long, 'rstar_net');
M_.param_names = char(M_.param_names, 'share_astar');
M_.param_names_tex = char(M_.param_names_tex, 'share\_astar');
M_.param_names_long = char(M_.param_names_long, 'share_astar');
M_.param_names = char(M_.param_names, 'alphan');
M_.param_names_tex = char(M_.param_names_tex, 'alphan');
M_.param_names_long = char(M_.param_names_long, 'alphan');
M_.param_names = char(M_.param_names, 'alphat');
M_.param_names_tex = char(M_.param_names_tex, 'alphat');
M_.param_names_long = char(M_.param_names_long, 'alphat');
M_.param_names = char(M_.param_names, 'alphag');
M_.param_names_tex = char(M_.param_names_tex, 'alphag');
M_.param_names_long = char(M_.param_names_long, 'alphag');
M_.param_names = char(M_.param_names, 'deltan');
M_.param_names_tex = char(M_.param_names_tex, 'deltan');
M_.param_names_long = char(M_.param_names_long, 'deltan');
M_.param_names = char(M_.param_names, 'deltat');
M_.param_names_tex = char(M_.param_names_tex, 'deltat');
M_.param_names_long = char(M_.param_names_long, 'deltat');
M_.param_names = char(M_.param_names, 'deltag');
M_.param_names_tex = char(M_.param_names_tex, 'deltag');
M_.param_names_long = char(M_.param_names_long, 'deltag');
M_.param_names = char(M_.param_names, 'rhoyt');
M_.param_names_tex = char(M_.param_names_tex, 'rhoyt');
M_.param_names_long = char(M_.param_names_long, 'rhoyt');
M_.param_names = char(M_.param_names, 'rhozt');
M_.param_names_tex = char(M_.param_names_tex, 'rhozt');
M_.param_names_long = char(M_.param_names_long, 'rhozt');
M_.param_names = char(M_.param_names, 'kappan');
M_.param_names_tex = char(M_.param_names_tex, 'kappan');
M_.param_names_long = char(M_.param_names_long, 'kappan');
M_.param_names = char(M_.param_names, 'kappat');
M_.param_names_tex = char(M_.param_names_tex, 'kappat');
M_.param_names_long = char(M_.param_names_long, 'kappat');
M_.param_names = char(M_.param_names, 'epsilontilde');
M_.param_names_tex = char(M_.param_names_tex, 'epsilontilde');
M_.param_names_long = char(M_.param_names_long, 'epsilontilde');
M_.param_names = char(M_.param_names, 'psiopt');
M_.param_names_tex = char(M_.param_names_tex, 'psiopt');
M_.param_names_long = char(M_.param_names_long, 'psiopt');
M_.param_names = char(M_.param_names, 'ssigma');
M_.param_names_tex = char(M_.param_names_tex, 'ssigma');
M_.param_names_long = char(M_.param_names_long, 'ssigma');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'div');
M_.param_names_tex = char(M_.param_names_tex, 'div');
M_.param_names_long = char(M_.param_names_long, 'div');
M_.param_names = char(M_.param_names, 'nug');
M_.param_names_tex = char(M_.param_names_tex, 'nug');
M_.param_names_long = char(M_.param_names_long, 'nug');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'rf_net');
M_.param_names_tex = char(M_.param_names_tex, 'rf\_net');
M_.param_names_long = char(M_.param_names_long, 'rf_net');
M_.param_names = char(M_.param_names, 'rd_net');
M_.param_names_tex = char(M_.param_names_tex, 'rd\_net');
M_.param_names_long = char(M_.param_names_long, 'rd_net');
M_.param_names = char(M_.param_names, 'etadc');
M_.param_names_tex = char(M_.param_names_tex, 'etadc');
M_.param_names_long = char(M_.param_names_long, 'etadc');
M_.param_names = char(M_.param_names, 'varkappa');
M_.param_names_tex = char(M_.param_names_tex, 'varkappa');
M_.param_names_long = char(M_.param_names_long, 'varkappa');
M_.param_names = char(M_.param_names, 'bstarovery');
M_.param_names_tex = char(M_.param_names_tex, 'bstarovery');
M_.param_names_long = char(M_.param_names_long, 'bstarovery');
M_.param_names = char(M_.param_names, 'rdc_net');
M_.param_names_tex = char(M_.param_names_tex, 'rdc\_net');
M_.param_names_long = char(M_.param_names_long, 'rdc_net');
M_.param_names = char(M_.param_names, 'dovery');
M_.param_names_tex = char(M_.param_names_tex, 'dovery');
M_.param_names_long = char(M_.param_names_long, 'dovery');
M_.param_names = char(M_.param_names, 'dcovery');
M_.param_names_tex = char(M_.param_names_tex, 'dcovery');
M_.param_names_long = char(M_.param_names_long, 'dcovery');
M_.param_names = char(M_.param_names, 'grovery');
M_.param_names_tex = char(M_.param_names_tex, 'grovery');
M_.param_names_long = char(M_.param_names_long, 'grovery');
M_.param_names = char(M_.param_names, 'lambda1');
M_.param_names_tex = char(M_.param_names_tex, 'lambda1');
M_.param_names_long = char(M_.param_names_long, 'lambda1');
M_.param_names = char(M_.param_names, 'lambda2');
M_.param_names_tex = char(M_.param_names_tex, 'lambda2');
M_.param_names_long = char(M_.param_names_long, 'lambda2');
M_.param_names = char(M_.param_names, 'lambda3');
M_.param_names_tex = char(M_.param_names_tex, 'lambda3');
M_.param_names_long = char(M_.param_names_long, 'lambda3');
M_.param_names = char(M_.param_names, 'lambda4');
M_.param_names_tex = char(M_.param_names_tex, 'lambda4');
M_.param_names_long = char(M_.param_names_long, 'lambda4');
M_.param_names = char(M_.param_names, 'zzeta1');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta1');
M_.param_names_long = char(M_.param_names_long, 'zzeta1');
M_.param_names = char(M_.param_names, 'zzeta2');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta2');
M_.param_names_long = char(M_.param_names_long, 'zzeta2');
M_.param_names = char(M_.param_names, 'zzeta3');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta3');
M_.param_names_long = char(M_.param_names_long, 'zzeta3');
M_.param_names = char(M_.param_names, 'zzeta4');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta4');
M_.param_names_long = char(M_.param_names_long, 'zzeta4');
M_.param_names = char(M_.param_names, 'zzeta5');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta5');
M_.param_names_long = char(M_.param_names_long, 'zzeta5');
M_.param_names = char(M_.param_names, 'zzeta6');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta6');
M_.param_names_long = char(M_.param_names_long, 'zzeta6');
M_.param_names = char(M_.param_names, 'zzeta7');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta7');
M_.param_names_long = char(M_.param_names_long, 'zzeta7');
M_.param_names = char(M_.param_names, 'zzeta8');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta8');
M_.param_names_long = char(M_.param_names_long, 'zzeta8');
M_.param_names = char(M_.param_names, 'ginss');
M_.param_names_tex = char(M_.param_names_tex, 'ginss');
M_.param_names_long = char(M_.param_names_long, 'ginss');
M_.param_names = char(M_.param_names, 'gcfloor');
M_.param_names_tex = char(M_.param_names_tex, 'gcfloor');
M_.param_names_long = char(M_.param_names_long, 'gcfloor');
M_.param_names = char(M_.param_names, 'zfloor');
M_.param_names_tex = char(M_.param_names_tex, 'zfloor');
M_.param_names_long = char(M_.param_names_long, 'zfloor');
M_.param_names = char(M_.param_names, 'taucceiling');
M_.param_names_tex = char(M_.param_names_tex, 'taucceiling');
M_.param_names_long = char(M_.param_names_long, 'taucceiling');
M_.param_names = char(M_.param_names, 'taulceiling');
M_.param_names_tex = char(M_.param_names_tex, 'taulceiling');
M_.param_names_long = char(M_.param_names_long, 'taulceiling');
M_.param_names = char(M_.param_names, 'rhodeltag');
M_.param_names_tex = char(M_.param_names_tex, 'rhodeltag');
M_.param_names_long = char(M_.param_names_long, 'rhodeltag');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'varsigmaepsilon');
M_.param_names_tex = char(M_.param_names_tex, 'varsigmaepsilon');
M_.param_names_long = char(M_.param_names_long, 'varsigmaepsilon');
M_.param_names = char(M_.param_names, 'githreshold');
M_.param_names_tex = char(M_.param_names_tex, 'githreshold');
M_.param_names_long = char(M_.param_names_long, 'githreshold');
M_.param_names = char(M_.param_names, 'varco');
M_.param_names_tex = char(M_.param_names_tex, 'varco');
M_.param_names_long = char(M_.param_names_long, 'varco');
M_.param_names = char(M_.param_names, 'fco');
M_.param_names_tex = char(M_.param_names_tex, 'fco');
M_.param_names_long = char(M_.param_names_long, 'fco');
M_.param_names = char(M_.param_names, 'sayg');
M_.param_names_tex = char(M_.param_names_tex, 'sayg');
M_.param_names_long = char(M_.param_names_long, 'sayg');
M_.param_names = char(M_.param_names, 'rhof');
M_.param_names_tex = char(M_.param_names_tex, 'rhof');
M_.param_names_long = char(M_.param_names_long, 'rhof');
M_.param_names = char(M_.param_names, 'varrhor');
M_.param_names_tex = char(M_.param_names_tex, 'varrhor');
M_.param_names_long = char(M_.param_names_long, 'varrhor');
M_.param_names = char(M_.param_names, 'varrhopie');
M_.param_names_tex = char(M_.param_names_tex, 'varrhopie');
M_.param_names_long = char(M_.param_names_long, 'varrhopie');
M_.param_names = char(M_.param_names, 'varrhoy');
M_.param_names_tex = char(M_.param_names_tex, 'varrhoy');
M_.param_names_long = char(M_.param_names_long, 'varrhoy');
M_.param_names = char(M_.param_names, 'xit');
M_.param_names_tex = char(M_.param_names_tex, 'xit');
M_.param_names_long = char(M_.param_names_long, 'xit');
M_.param_names = char(M_.param_names, 'xin');
M_.param_names_tex = char(M_.param_names_tex, 'xin');
M_.param_names_long = char(M_.param_names_long, 'xin');
M_.param_names = char(M_.param_names, 'zzeta');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta');
M_.param_names_long = char(M_.param_names_long, 'zzeta');
M_.param_names = char(M_.param_names, 'piess');
M_.param_names_tex = char(M_.param_names_tex, 'piess');
M_.param_names_long = char(M_.param_names_long, 'piess');
M_.param_names = char(M_.param_names, 'f');
M_.param_names_tex = char(M_.param_names_tex, 'f');
M_.param_names_long = char(M_.param_names_long, 'f');
M_.param_names = char(M_.param_names, 'exdebt');
M_.param_names_tex = char(M_.param_names_tex, 'exdebt');
M_.param_names_long = char(M_.param_names_long, 'exdebt');
M_.param_names = char(M_.param_names, 'k1');
M_.param_names_tex = char(M_.param_names_tex, 'k1');
M_.param_names_long = char(M_.param_names_long, 'k1');
M_.param_names = char(M_.param_names, 'k2');
M_.param_names_tex = char(M_.param_names_tex, 'k2');
M_.param_names_long = char(M_.param_names_long, 'k2');
M_.param_names = char(M_.param_names, 'fstar_foor');
M_.param_names_tex = char(M_.param_names_tex, 'fstar\_foor');
M_.param_names_long = char(M_.param_names_long, 'fstar_foor');
M_.param_names = char(M_.param_names, 'ggamma_add');
M_.param_names_tex = char(M_.param_names_tex, 'ggamma\_add');
M_.param_names_long = char(M_.param_names_long, 'ggamma_add');
M_.param_names = char(M_.param_names, 'chiT');
M_.param_names_tex = char(M_.param_names_tex, 'chiT');
M_.param_names_long = char(M_.param_names_long, 'chiT');
M_.param_names = char(M_.param_names, 'rhoxx');
M_.param_names_tex = char(M_.param_names_tex, 'rhoxx');
M_.param_names_long = char(M_.param_names_long, 'rhoxx');
M_.param_names = char(M_.param_names, 'rhorem');
M_.param_names_tex = char(M_.param_names_tex, 'rhorem');
M_.param_names_long = char(M_.param_names_long, 'rhorem');
M_.param_names = char(M_.param_names, 'nutt');
M_.param_names_tex = char(M_.param_names_tex, 'nutt');
M_.param_names_long = char(M_.param_names_long, 'nutt');
M_.param_names = char(M_.param_names, 'varphiT');
M_.param_names_tex = char(M_.param_names_tex, 'varphiT');
M_.param_names_long = char(M_.param_names_long, 'varphiT');
M_.param_names = char(M_.param_names, 'oil_elast');
M_.param_names_tex = char(M_.param_names_tex, 'oil\_elast');
M_.param_names_long = char(M_.param_names_long, 'oil_elast');
M_.param_names = char(M_.param_names, 'mm_other');
M_.param_names_tex = char(M_.param_names_tex, 'mm\_other');
M_.param_names_long = char(M_.param_names_long, 'mm_other');
M_.param_names = char(M_.param_names, 'dummy_swf');
M_.param_names_tex = char(M_.param_names_tex, 'dummy\_swf');
M_.param_names_long = char(M_.param_names_long, 'dummy_swf');
M_.param_names = char(M_.param_names, 'dummy_dgt');
M_.param_names_tex = char(M_.param_names_tex, 'dummy\_dgt');
M_.param_names_long = char(M_.param_names_long, 'dummy_dgt');
M_.param_names = char(M_.param_names, 'dummy_abcap');
M_.param_names_tex = char(M_.param_names_tex, 'dummy\_abcap');
M_.param_names_long = char(M_.param_names_long, 'dummy_abcap');
M_.param_names = char(M_.param_names, 'dummy_extrans');
M_.param_names_tex = char(M_.param_names_tex, 'dummy\_extrans');
M_.param_names_long = char(M_.param_names_long, 'dummy_extrans');
M_.param_names = char(M_.param_names, 'dummy_exgc');
M_.param_names_tex = char(M_.param_names_tex, 'dummy\_exgc');
M_.param_names_long = char(M_.param_names_long, 'dummy_exgc');
M_.param_names = char(M_.param_names, 'ind_extauc');
M_.param_names_tex = char(M_.param_names_tex, 'ind\_extauc');
M_.param_names_long = char(M_.param_names_long, 'ind_extauc');
M_.param_names = char(M_.param_names, 'ind_extaul');
M_.param_names_tex = char(M_.param_names_tex, 'ind\_extaul');
M_.param_names_long = char(M_.param_names_long, 'ind_extaul');
M_.param_names = char(M_.param_names, 'psirot');
M_.param_names_tex = char(M_.param_names_tex, 'psirot');
M_.param_names_long = char(M_.param_names_long, 'psirot');
M_.param_names = char(M_.param_names, 'chiFF');
M_.param_names_tex = char(M_.param_names_tex, 'chiFF');
M_.param_names_long = char(M_.param_names_long, 'chiFF');
M_.param_names = char(M_.param_names, 'share_impff');
M_.param_names_tex = char(M_.param_names_tex, 'share\_impff');
M_.param_names_long = char(M_.param_names_long, 'share_impff');
M_.param_names = char(M_.param_names, 'share_impk');
M_.param_names_tex = char(M_.param_names_tex, 'share\_impk');
M_.param_names_long = char(M_.param_names_long, 'share_impk');
M_.param_names = char(M_.param_names, 'EPSILONG');
M_.param_names_tex = char(M_.param_names_tex, 'EPSILONG');
M_.param_names_long = char(M_.param_names_long, 'EPSILONG');
M_.param_names = char(M_.param_names, 'alphagg');
M_.param_names_tex = char(M_.param_names_tex, 'alphagg');
M_.param_names_long = char(M_.param_names_long, 'alphagg');
M_.param_names = char(M_.param_names, 'rhoMM');
M_.param_names_tex = char(M_.param_names_tex, 'rhoMM');
M_.param_names_long = char(M_.param_names_long, 'rhoMM');
M_.param_names = char(M_.param_names, 'mmthreshold');
M_.param_names_tex = char(M_.param_names_tex, 'mmthreshold');
M_.param_names_long = char(M_.param_names_long, 'mmthreshold');
M_.param_names = char(M_.param_names, 'taxC');
M_.param_names_tex = char(M_.param_names_tex, 'taxC');
M_.param_names_long = char(M_.param_names_long, 'taxC');
M_.param_names = char(M_.param_names, 'taxL');
M_.param_names_tex = char(M_.param_names_tex, 'taxL');
M_.param_names_long = char(M_.param_names_long, 'taxL');
M_.param_names = char(M_.param_names, 'ty');
M_.param_names_tex = char(M_.param_names_tex, 'ty');
M_.param_names_long = char(M_.param_names_long, 'ty');
M_.param_names = char(M_.param_names, 'totax');
M_.param_names_tex = char(M_.param_names_tex, 'totax');
M_.param_names_long = char(M_.param_names_long, 'totax');
M_.param_names = char(M_.param_names, 'chiX');
M_.param_names_tex = char(M_.param_names_tex, 'chiX');
M_.param_names_long = char(M_.param_names_long, 'chiX');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 174;
M_.param_nbr = 107;
M_.orig_endo_nbr = 174;
M_.aux_vars = [];
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('EBASELINE_static');
erase_compiled_function('EBASELINE_dynamic');
M_.orig_eq_nbr = 174;
M_.eq_nbr = 174;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 30 204;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 1 36 205;
 2 37 206;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 207;
 3 43 0;
 4 44 208;
 0 45 209;
 0 46 0;
 0 47 0;
 0 48 210;
 0 49 0;
 5 50 0;
 6 51 211;
 0 52 212;
 0 53 0;
 0 54 0;
 7 55 0;
 8 56 0;
 9 57 0;
 0 58 0;
 10 59 0;
 11 60 0;
 12 61 0;
 0 62 0;
 13 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 14 69 0;
 15 70 0;
 0 71 0;
 0 72 0;
 16 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 17 78 0;
 0 79 0;
 18 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 19 92 0;
 0 93 0;
 20 94 0;
 21 95 0;
 22 96 0;
 23 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 0;
 0 102 0;
 0 103 0;
 0 104 0;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 0 109 0;
 0 110 213;
 0 111 214;
 0 112 215;
 0 113 0;
 0 114 216;
 24 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 0;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 0;
 0 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 0 149 0;
 0 150 0;
 0 151 0;
 0 152 0;
 0 153 0;
 25 154 0;
 26 155 217;
 0 156 0;
 0 157 218;
 0 158 0;
 0 159 0;
 0 160 0;
 0 161 0;
 0 162 0;
 0 163 0;
 0 164 0;
 0 165 0;
 0 166 0;
 0 167 0;
 0 168 0;
 0 169 0;
 0 170 0;
 0 171 0;
 0 172 0;
 0 173 0;
 0 174 0;
 27 175 0;
 28 176 0;
 0 177 0;
 0 178 0;
 0 179 0;
 0 180 0;
 0 181 0;
 29 182 0;
 0 183 0;
 0 184 0;
 0 185 0;
 0 186 0;
 0 187 0;
 0 188 0;
 0 189 0;
 0 190 0;
 0 191 0;
 0 192 0;
 0 193 0;
 0 194 0;
 0 195 0;
 0 196 0;
 0 197 0;
 0 198 0;
 0 199 0;
 0 200 0;
 0 201 0;
 0 202 0;
 0 203 0;]';
M_.nstatic = 135;
M_.nfwrd   = 10;
M_.npred   = 24;
M_.nboth   = 5;
M_.nsfwrd   = 15;
M_.nspred   = 29;
M_.ndynamic   = 39;
M_.equations_tags = {
  1 , 'name' , 'Exogenous debt' ;
  2 , 'name' , 'Exogenous aggregate labour' ;
  31 , 'name' , 'check' ;
  39 , 'name' , 'check' ;
  60 , 'name' , 'check2' ;
  82 , 'name' , 'Labour income tax rate rule' ;
  97 , 'name' , 'check' ;
  103 , 'name' , 'Grants' ;
  128 , 'name' , 'check' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(174, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(107, 1);
M_.NNZDerivatives = [677; 0; -1];
exogenous_variables = xlsread('inputs.xlsx',2,'B9:AR1008');
time_line = exogenous_variables(2:1000,1);
plot_periods  = enddate-startdate+1;
dummy_periods = zeros(1,999);
dummy_periods(1,1:plot_periods-1)=1;
dummy_periods = dummy_periods';
calib_shock_periods = zeros(1,999);
calib_shock_periods(1,1:plot_periods*10-1)=1;
calib_shock_periods = calib_shock_periods';
if nr_y_opt==1
ntrl_rsrc = exogenous_variables(:,2);
elseif nr_y_opt==2
ntrl_rsrc = exogenous_variables(:,3);
elseif nr_y_opt==3
ntrl_rsrc = exogenous_variables(:,4);
else 
ntrl_rsrc = zeros(1,1000)';
end
if nr_p_opt==1
rsrc_prce = exogenous_variables(:,5);
elseif nr_p_opt==2
rsrc_prce = exogenous_variables(:,6);
elseif nr_p_opt==3
rsrc_prce = exogenous_variables(:,7);
else 
rsrc_prce = ones(1,1000)';
end
if pub_inv_opt==1
invt_xpdt = exogenous_variables(:,8);
elseif pub_inv_opt==2
invt_xpdt = exogenous_variables(:,9);
elseif pub_inv_opt==3
invt_xpdt = exogenous_variables(:,10);
else 
invt_xpdt = zeros(1,1000)';
end
if pub_inv_eff_opt==1
efficiency_parameter = exogenous_variables(:,11);
elseif pub_inv_eff_opt==2
efficiency_parameter = exogenous_variables(:,12);
elseif pub_inv_eff_opt==3
efficiency_parameter = exogenous_variables(:,13);
else 
efficiency_parameter = zeros(1,1000)';
end
if pub_cons_opt==1
gov_cons = exogenous_variables(:,14);
elseif pub_cons_opt==2
gov_cons = exogenous_variables(:,15);
elseif pub_cons_opt==3
gov_cons = exogenous_variables(:,16);
else 
gov_cons = zeros(1,1000)';
end
if pub_tran_opt==1
ex_transfers = exogenous_variables(:,17);
elseif pub_tran_opt==2
ex_transfers = exogenous_variables(:,18);
elseif pub_tran_opt==3
ex_transfers = exogenous_variables(:,19);
else 
ex_transfers = zeros(1,1000)';
end
if d_cons_tax_opt==1
consumption_tax_imposed = exogenous_variables(2:end,20);
elseif d_cons_tax_opt==2
consumption_tax_imposed = exogenous_variables(2:end,21);
elseif d_cons_tax_opt==3
consumption_tax_imposed = exogenous_variables(2:end,22);
else 
consumption_tax_imposed = zeros(1,999)';
end
if d_lab_tax_opt==1
labour_tax_imposed = exogenous_variables(2:end,23);
elseif d_lab_tax_opt==2
labour_tax_imposed = exogenous_variables(2:end,24);
elseif d_lab_tax_opt==3
labour_tax_imposed = exogenous_variables(2:end,25);
else 
labour_tax_imposed = zeros(1,999)';
end
if cons_debt_opt==1
conc_debt = exogenous_variables(:,26);
elseif cons_debt_opt==2
conc_debt = exogenous_variables(:,27);
elseif cons_debt_opt==3
conc_debt = exogenous_variables(:,28);
else 
conc_debt = zeros(1,1000)';
end
if grants_opt ==1
frgn_grts = exogenous_variables(:,29);
elseif grants_opt ==2
frgn_grts = exogenous_variables(:,30);
elseif grants_opt ==3
frgn_grts = exogenous_variables(:,31);
else 
frgn_grts = zeros(1,1000)';
end
if risk_prem_opt==1
ex_rprem = exogenous_variables(:,32);
elseif risk_prem_opt==2
ex_rprem = exogenous_variables(:,33);
elseif risk_prem_opt==3
ex_rprem = exogenous_variables(:,34);
else 
ex_rprem = zeros(1,1000)';
end
if remit_opt==1
ex_remit = exogenous_variables(:,35);
elseif remit_opt==2
ex_remit = exogenous_variables(:,36);
elseif remit_opt==3
ex_remit = exogenous_variables(:,37);
else 
ex_remit = zeros(1,1000)';
end
if x_opt==1
ex_exports = exogenous_variables(:,38);
elseif x_opt==2
ex_exports = exogenous_variables(:,39);
elseif x_opt==3
ex_exports = exogenous_variables(:,40);
else 
ex_exports = zeros(1,1000)';
end
ntrl_rsrc_dev            =  ntrl_rsrc(2:1000,1)                                                       .*dummy_periods   ./100;
rsrc_prce_dev            =  (log(rsrc_prce(2:1000,1)./rsrc_prce(1,1)))                                .*dummy_periods;
invt_xpdt_dev            =  (invt_xpdt(2:1000,1) - invt_xpdt(1,1)*ones(999,1))                        .*dummy_periods   ./100;
efficiency_parameter_dev =  (efficiency_parameter(2:1000,1) - efficiency_parameter(1,1)*ones(999,1) ) .*dummy_periods   ./100;
gov_cons_dev             =  (gov_cons(2:1000,1) - gov_cons(1,1)*ones(999,1))                          .*dummy_periods   ./100;
ex_transfers_dev         =  (ex_transfers(2:1000,1) - ex_transfers(1,1)*ones(999,1))                  .*dummy_periods   ./100;
consumption_tax_imposed  =  consumption_tax_imposed                                                   .*dummy_periods   ./100;
labour_tax_imposed       =  labour_tax_imposed                                                        .*dummy_periods   ./100;
conc_debt_dev            =  (conc_debt(2:1000,1) - conc_debt(1,1)*ones(999,1))                        .*dummy_periods   ./100;
frgn_grts_dev            =  (frgn_grts(2:1000,1) - frgn_grts(1,1)*ones(999,1))                        .*dummy_periods   ./100;
ex_rprem_dev             =  (ex_rprem(2:1000,1) - ex_rprem(1,1)*ones(999,1))                          .*dummy_periods   ./100;
ex_remit_dev             =  (ex_remit(2:1000,1) - ex_remit(1,1)*ones(999,1))                          .*dummy_periods   ./100;
ex_exports_dev           =  (ex_exports(2:1000,1) - ex_exports(1,1)*ones(999,1))                      .*dummy_periods   ./100;
ntrl_rsrc_dev(isnan(ntrl_rsrc_dev))=0;
rsrc_prce_dev(isnan(rsrc_prce_dev))=0;
invt_xpdt_dev(isnan(invt_xpdt_dev))=0;
efficiency_parameter_dev(isnan(efficiency_parameter_dev))=0;
gov_cons_dev(isnan(gov_cons_dev))=0;
ex_transfers_dev(isnan(ex_transfers_dev))=0;
consumption_tax_imposed(isnan(consumption_tax_imposed))=0;
labour_tax_imposed(isnan(labour_tax_imposed))=0;
conc_debt_dev(isnan(conc_debt_dev))=0;
frgn_grts_dev(isnan(frgn_grts_dev))=0;
ex_rprem_dev(isnan(ex_rprem_dev))=0;
ex_remit_dev(isnan(ex_remit_dev))=0;
ex_exports_dev(isnan(ex_exports_dev))=0;
if lab_opt==1
load('calibrated_shocks.mat','lab_shock_opt1');
labour_supply_shock  =  lab_shock_opt1(2:end,:) .*dummy_periods;
labour_supply_shock(isnan(labour_supply_shock))=0;
elseif lab_opt==2
load('calibrated_shocks.mat','lab_shock_opt2');
labour_supply_shock  =  lab_shock_opt2(2:end,:) .*dummy_periods;
labour_supply_shock(isnan(labour_supply_shock))=0;
elseif lab_opt==3
load('calibrated_shocks.mat','lab_shock_opt3');
labour_supply_shock  =  lab_shock_opt3(2:end,:) .*dummy_periods;
labour_supply_shock(isnan(labour_supply_shock))=0;
else 
labour_supply_shock = zeros(1,999)';
end
ad_hoc_debt = ad_hoc_proj(1:end,1);
ad_hoc_gdp = ad_hoc_proj(1:end,2);
ad_hoc_gdp(plot_periods+1:end,1) = old_growth(plot_periods+1:end,1);
ad_hoc_gdp_dev = (ad_hoc_gdp(2:1000,1) - ad_hoc_gdp(1,1));
ad_hoc_debt_dev = (ad_hoc_debt(2:1000,1) - ad_hoc_debt(1,1));
ad_hoc_gdp_dev(isnan(ad_hoc_gdp_dev))=0;
ad_hoc_debt_dev(isnan(ad_hoc_debt_dev))=0;
M_.params( 1 ) = 0;
ggamma = M_.params( 1 );
M_.params( 80 ) = ggamma_iii/100;
ggamma_add = M_.params( 80 );
M_.params( 2 ) = share_exp_iii;
share_exp = M_.params( 2 );
M_.params( 3 ) = share_imp_iii;
share_imp = M_.params( 3 );
M_.params( 4 ) = share_gc_iii;
share_gc = M_.params( 4 );
M_.params( 5 ) = share_gc_iii+share_gi_iii;
share_g = M_.params( 5 );
M_.params( 6 ) = share_i_iii;
share_i = M_.params( 6 );
M_.params( 7 ) = share_gdpo_iii;
share_gdpo = M_.params( 7 );
M_.params( 8 ) = share_fstar_iii;
share_fstar = M_.params( 8 );
M_.params( 9 ) = share_b_iii;
share_b = M_.params( 9 );
M_.params( 10 ) = trad_g_iii/100;
trad_g = M_.params( 10 );
M_.params( 11 ) = trad_c_iii/100;
trad_c = M_.params( 11 );
M_.params( 12 ) = r_net_iii/100;
r_net = M_.params( 12 );
M_.params( 13 ) = rstar_net_iii/100;
rstar_net = M_.params( 13 );
M_.params( 35 ) = rd_net_iii/100;
rd_net = M_.params( 35 );
M_.params( 14 ) = share_astar_iii;
share_astar = M_.params( 14 );
M_.params( 15 ) = alphan_iii/100;
alphan = M_.params( 15 );
M_.params( 16 ) = alphat_iii/100;
alphat = M_.params( 16 );
M_.params( 17 ) = alphag_iii;
alphag = M_.params( 17 );
M_.params( 18 ) = deltan_iii/100;
deltan = M_.params( 18 );
M_.params( 19 ) = deltat_iii/100;
deltat = M_.params( 19 );
M_.params( 20 ) = deltag_iii/100;
deltag = M_.params( 20 );
M_.params( 21 ) = rhoyt_iii;
rhoyt = M_.params( 21 );
M_.params( 22 ) = rhozt_iii;
rhozt = M_.params( 22 );
M_.params( 23 ) = kappan_iii;
kappan = M_.params( 23 );
M_.params( 24 ) = kappat_iii;
kappat = M_.params( 24 );
M_.params( 25 ) = epsilontilde_iii/100;
epsilontilde = M_.params( 25 );
M_.params( 26 ) = psiopt_iii;
psiopt = M_.params( 26 );
M_.params( 95 ) = psirot_iii;
psirot = M_.params( 95 );
M_.params( 27 ) = ssigma_iii;
ssigma = M_.params( 27 );
M_.params( 28 ) = rho_iii;
rho = M_.params( 28 );
M_.params( 29 ) = omega_iii/100;
omega = M_.params( 29 );
M_.params( 30 ) = chi_iii;
chi = M_.params( 30 );
M_.params( 31 ) = div_iii/100;
div = M_.params( 31 );
M_.params( 105 ) = ty_iii/100;
ty = M_.params( 105 );
M_.params( 106 ) = totax_iii/100;
totax = M_.params( 106 );
M_.params( 103 ) = taxC_iii/100;
taxC = M_.params( 103 );
M_.params( 32 ) = nug_iii;
nug = M_.params( 32 );
M_.params( 33 ) = eta_iii;
eta = M_.params( 33 );
M_.params( 34 ) = rf_net_iii/100;
rf_net = M_.params( 34 );
M_.params( 36 ) = etadc_iii;
etadc = M_.params( 36 );
M_.params( 37 ) = varkappa_iii/100;
varkappa = M_.params( 37 );
M_.params( 38 ) = bstarovery_iii/100;
bstarovery = M_.params( 38 );
M_.params( 39 ) = rdc_net_iii/100;
rdc_net = M_.params( 39 );
M_.params( 40 ) = dovery_iii/100;
dovery = M_.params( 40 );
M_.params( 41 ) = dcovery_iii/100;
dcovery = M_.params( 41 );
M_.params( 42 ) = grovery_iii/100;
grovery = M_.params( 42 );
M_.params( 43 ) = lambda1_iii/100;
lambda1 = M_.params( 43 );
M_.params( 44 ) = lambda2_iii/100;
lambda2 = M_.params( 44 );
M_.params( 45 ) = lambda3_iii/100;
lambda3 = M_.params( 45 );
M_.params( 46 ) = lambda4_iii/100;
lambda4 = M_.params( 46 );
M_.params( 47 ) = zzeta1_iii;
zzeta1 = M_.params( 47 );
M_.params( 48 ) = zzeta2_iii;
zzeta2 = M_.params( 48 );
M_.params( 49 ) = zzeta3_iii;
zzeta3 = M_.params( 49 );
M_.params( 50 ) = zzeta4_iii;
zzeta4 = M_.params( 50 );
M_.params( 51 ) = zzeta5_iii;
zzeta5 = M_.params( 51 );
M_.params( 52 ) = zzeta6_iii;
zzeta6 = M_.params( 52 );
M_.params( 53 ) = zzeta7_iii;
zzeta7 = M_.params( 53 );
M_.params( 54 ) = zzeta8_iii;
zzeta8 = M_.params( 54 );
M_.params( 76 ) = exdebt_iii;
exdebt = M_.params( 76 );
M_.params( 55 ) = ginss_iii/100;
ginss = M_.params( 55 );
M_.params( 56 ) = gcfloor_iii/100;
gcfloor = M_.params( 56 );
M_.params( 57 ) = zfloor_iii/100;
zfloor = M_.params( 57 );
M_.params( 58 ) = taucceiling_iii/100;
taucceiling = M_.params( 58 );
M_.params( 59 ) = taulceiling_iii/100;
taulceiling = M_.params( 59 );
M_.params( 60 ) = rhodeltag_iii;
rhodeltag = M_.params( 60 );
M_.params( 61 ) = phi_iii;
phi = M_.params( 61 );
M_.params( 62 ) = varsigmaepsilon_iii;
varsigmaepsilon = M_.params( 62 );
M_.params( 63 ) = githreshold_iii/100;
githreshold = M_.params( 63 );
M_.params( 64 ) = varco_iii/100;
varco = M_.params( 64 );
M_.params( 65 ) = fco_iii/100;
fco = M_.params( 65 );
M_.params( 66 ) = sayg_iii;
sayg = M_.params( 66 );
M_.params( 67 ) = rhof_iii/100;
rhof = M_.params( 67 );
M_.params( 68 ) = varrhor_iii;
varrhor = M_.params( 68 );
M_.params( 69 ) = varrhopie_iii;
varrhopie = M_.params( 69 );
M_.params( 70 ) = varrhoy_iii;
varrhoy = M_.params( 70 );
M_.params( 71 ) = xit_iii;
xit = M_.params( 71 );
M_.params( 72 ) = xin_iii;
xin = M_.params( 72 );
M_.params( 73 ) = zzeta_iii;
zzeta = M_.params( 73 );
M_.params( 74 ) = piess_iii/100;
piess = M_.params( 74 );
M_.params( 104 ) = taxL_iii/100;
taxL = M_.params( 104 );
M_.params( 75 ) = f_iii/100;
f = M_.params( 75 );
M_.params( 77 ) = k1_iii;
k1 = M_.params( 77 );
M_.params( 78 ) = k2_iii;
k2 = M_.params( 78 );
M_.params( 79 ) = fstar_foor_iii/100;
fstar_foor = M_.params( 79 );
M_.params( 81 ) = chiT_iii;
chiT = M_.params( 81 );
M_.params( 82 ) = 0.50;
rhoxx = M_.params( 82 );
M_.params( 83 ) = 0.50;
rhorem = M_.params( 83 );
M_.params( 84 ) = nutt_iii/100;
nutt = M_.params( 84 );
M_.params( 85 ) = varphiT_iii/100;
varphiT = M_.params( 85 );
M_.params( 86 ) = oil_elast_iii;
oil_elast = M_.params( 86 );
M_.params( 97 ) = share_impff_iii/100;
share_impff = M_.params( 97 );
M_.params( 98 ) = share_impk_iii/100;
share_impk = M_.params( 98 );
M_.params( 107 ) = chiX_iii;
chiX = M_.params( 107 );
M_.params( 96 ) = chiFF_iii;
chiFF = M_.params( 96 );
M_.params( 99 ) = EPSILONG_iii;
EPSILONG = M_.params( 99 );
M_.params( 100 ) = alphagg_iii;
alphagg = M_.params( 100 );
M_.params( 101 ) = rhoMM_iii;
rhoMM = M_.params( 101 );
M_.params( 102 ) = 0.02;
mmthreshold = M_.params( 102 );
M_.params( 88 ) = 1;
dummy_swf = M_.params( 88 );
M_.params( 89 ) = 0;
dummy_dgt = M_.params( 89 );
M_.params( 90 ) = 0;
dummy_abcap = M_.params( 90 );
M_.params( 92 ) = 1;
dummy_exgc = M_.params( 92 );
M_.params( 91 ) = 1;
dummy_extrans = M_.params( 91 );
M_.params( 93 ) = 1;
ind_extauc = M_.params( 93 );
M_.params( 94 ) = 1;
ind_extaul = M_.params( 94 );
%
% SHOCKS instructions
%
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',1,'multiplicative',0,'periods',1:999,'value',ad_hoc_debt_dev) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',2,'multiplicative',0,'periods',1:999,'value',ex_exports_dev) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',3,'multiplicative',0,'periods',1:999,'value',ad_hoc_gdp_dev) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',4,'multiplicative',0,'periods',1:999,'value',invt_xpdt_dev) ];
M_.exo_det_length = 0;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.periods = 1000;
options_.simul.maxit = 20;
options_.stack_solve_algo = 6;
perfect_foresight_setup;
perfect_foresight_solver;
save('EBASELINE_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EBASELINE_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EBASELINE_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EBASELINE_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EBASELINE_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('EBASELINE_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('EBASELINE_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
