all_names = char('Pub. inv. to GDP (\Delta from SS, pp)', 'Foreign aid change (% of GDP)', 'Grants to GDP (\Delta from SS, pp)',... 
    'Rel. price of nontradables (%\Delta from SS)', 'Cons. tax rate (\Delta from SS, pp)', 'Lab income tax rate (\Delta from SS, pp)', 'Transfers to GDP (\Delta from SS, pp)',... 
    'Gov. cons. to GDP (\Delta from SS, pp)', 'Net real interest rate (\Delta from SS, pp)', 'Priv. inv. to GDP (\Delta from SS, pp)', 'Priv. cons. to GDP (\Delta from SS, pp)',... 
    'Real wage (%\Delta from SS)', 'Labour (%\Delta from SS)', 'Public capital (%\Delta from SS)', 'Priv. capital (%\Delta from SS)', 'GDP growth (%)',... 
    'Tradable output (%\Delta from SS)', 'Nontradable output (%\Delta from SS)', 'Resource output (level)', 'Resource output growth (YoY %)', 'Concessional debt to GDP (\Delta from SS, pp)',... 
    'External commercial debt to GDP (\Delta from SS, pp)', 'Domestic debt to GDP (\Delta from SS, pp)', 'Total public debt to GDP (\Delta from SS, pp)', 'Real exchange rate (%\Delta from SS)',...
    'Resource price (level)', 'Pub invest. efficiency (%)',... 
    'Non-resouce output (%\Delta from SS)', 'Current account deficit to GDP (\Delta from SS, pp)', 'Pub. inv. (%\Delta from SS)', 'Transfers (% of Y_0)',... 
    'Gov. cons. (% of Y_0)', 'Transfers (%\Delta from SS)', 'Gov. cons. (%\Delta from SS)', 'Resource output (%\Delta from SS)', 'Resource revenue (% of tot. rev.)',... 
    'Non-resource GDP growth (%)', 'CPI inflation (%)', 'Resource output (level)', 'Resource price (level)', 'Sovereign risk premium (\Delta, pp)',...
    'Remit. to GDP (\Delta from SS, pp)', 'Exports to GDP (\Delta from SS, pp)','Total GDP growth (YoY %)', 'Total gov. revenue to GDP (\Delta from SS, pp)','CROT to GDP (\Delta from SS, pp)','COPT to GDP (\Delta from SS, pp)');

plot_periods = enddate-startdate+1;

all_simulations_matrix =[GISHARE_CHANGE ASTARSHARE_CHANGE GRSHARE_CHANGE PN_DEV TAUC_DEV TAUL_DEV ZSHARE_CHANGE GCSHARE_CHANGE R_NET... 
                         INV_DEV C_DEV W_DEV L_DEV KG_DEV K_DEV Y_GROWTH YT_DEV YN_DEV YO YO_YOY DSHARE_DEV DCSHARE_DEV BSHARE_DEV TOTPUBDEBT_PER... 
                         S_DEV PO EPSILON_PER  YNON_DEV CADSHARE_PER GI_DEV Z_SHAREY GC_SHAREY Z_DEV... 
                         GC_DEV YOTILDE_DEV TAXO_SHARETAX YNON_GROWTH PIE_RATE [ntrl_rsrc;zeros(2,1)] [rsrc_prce;zeros(2,1)] SRP_CHANGE REMIT_CHANGE XX_CHANGE Y_GROWTH  TAXSHARE_CHANGE CROT_DEV COPT_DEV];

[mmm,nnn] = size(select_strs); 
             
for iii = 1 : mmm
    ind=find(ismember(all_strs, select_strs(iii)));
    select_names(iii,:) = all_names(ind,:);
    select_simulations_matrix(:,iii) = all_simulations_matrix(:,ind); 
end

years = startdate:1:enddate;
labels = ['Years'; cellstr(select_names)]';
export_scenario1 = [years' select_simulations_matrix(1:plot_periods,:)];
writematrix(export_scenario1,'output.xls','Sheet',strcat('Scenario ',int2str(scenario_num)),'Range','A2');
writecell(labels,'output.xls','Sheet',strcat('Scenario ',int2str(scenario_num)),'Range','A1:Z1');
